### PR TITLE
Fix some problems

### PR DESCRIPTION
**Pull request by lajiao117**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

 >/kind bug

**What this PR does / why we need it**:
Fix some problems. when update csi image,the csi container may not exit
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE
```release-note
none
```

### CODE REVIEW

**Comment by MeinhardZhou** [comment]
@lajiao117 
Can you update the commit more standardized? 
Please Follow https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines

**Comment by lajiao117** [comment]
> @lajiao117 Can you update the commit message more standardized? Please Follow https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelines

@MeinhardZhou  ok, updated the commit message done.

**Review by MeinhardZhou — APPROVED** [review]

**Pull request merged**
